#!/bin/bash
. config.local

BASEDIR=`pwd`
HOSTIP=`hostname  -I | cut -f 1 -d ' '`

podman run -d --rm --name koji-postgres \
    -p 5432:5432 \
    -e POSTGRES_USER=koji \
    -e POSTGRES_DB=koji \
    -e POSTGRES_HOST_AUTH_METHOD=password \
    -e POSTGRES_PASSWORD=mypassword \
    -e DB_SCHEMA=/opt/schemas/schema.sql \
    -v $BASEDIR/db/data:/var/lib/postgresql/data:z \
    -v $BASEDIR/db:/docker-entrypoint-initdb.d:z \
    -v $CODEDIR:/opt:z postgres:12 && sleep 2

podman run -it --rm \
    --security-opt label=disable \
    -v $BASEDIR/basedir:/mnt/koji:z \
    -v $BASEDIR/hub:/opt/cfg:z \
    -v $CODEDIR:/opt/koji \
    -p 8080:80 \
    -p 8081:443 \
    -h localhost.localdomain \
    --name koji-hub \
    --env=HOSTIP=$HOSTIP \
    koji \
    /opt/cfg/entrypoint.sh
