#!/bin/bash

. config.local

USE_CONSOLE="-it"
REPLACE=""
while getopts dhr option ; do
    case "${option}" in
        h)
            echo "Usage: run-hub [-h] [-d]"
            echo " -h: prints this help"
            echo " -d: detaches from the console"
            echo " -r: replaces running containers (koji-postgres, koji-hub)"
            exit 2
            ;;
        d)
            USE_CONSOLE="-d"
            ;;
        r)  
            REPLACE="--replace"
            ;;
        *)
            echo "Unknown option"
            exit 1
            ;;
    esac
done

BASEDIR=`pwd`
HOSTIP=`hostname  -I | cut -f 1 -d ' '`

podman pod create $REPLACE -p 5432:5432 -p 8080:80 -p 8081:443 koji-dev

podman run -d --rm --name koji-postgres $REPLACE \
    --pod=koji-dev \
    -e POSTGRES_USER=koji \
    -e POSTGRES_DB=koji \
    -e POSTGRES_HOST_AUTH_METHOD=password \
    -e POSTGRES_PASSWORD=mypassword \
    -e DB_SCHEMA=/opt/schemas/schema.sql \
    -v $BASEDIR/db/data:/var/lib/postgresql/data:z \
    -v $BASEDIR/db:/docker-entrypoint-initdb.d:z \
    -v $CODEDIR:/opt:z postgres:17 && sleep 2

podman run $USE_CONSOLE --rm $REPLACE \
    --pod=koji-dev \
    --security-opt label=disable \
    -v $BASEDIR/basedir:/mnt/koji:z \
    -v $BASEDIR/hub:/opt/cfg:z \
    -v $CODEDIR:/opt/koji \
    --name koji-hub \
    --env=HOSTIP=$HOSTIP \
    koji \
    /opt/cfg/entrypoint.sh
